name: WakaTime Readme

on:
  schedule:
    # Runs at 12am UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/wakatime-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
